id: P003047
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23558
  title: ཡེ་བརྫུ་གཉན་པོའི་ཆོས་སྐོར།
  author: ''
  volumes:
    ec187b7ab30a4d8b88f34c3671017ce8:
      image_group_id: I2151
      title: ''
      volume_number: 1
      total_pages: 514
      base_file: v001.txt
